### PR TITLE
.Net 8 Support Added

### PR DESCRIPTION
**Pull request by KannanKrish**
I have added support for the .Net 8. Please review the changes at your side. I am happy for contributing.

### CODE REVIEW

**Comment by RadekVyM** [comment]
Hi @KannanKrish,

I really appreciate your effort, but I do not plan to update the library to .NET 8 yet.

I am currently working on a new, fairly large update ([dev branch](https://github.com/RadekVyM/SimpleToolkit/tree/dev)) which will take me some time to complete. I want to update the library to .NET 8 after all the planned features are implemented and after .NET 8 is released at least as RC.

I also want to take advantage of some of the changes that were made in .NET 8 MAUI and that should simplify implementation of some SimpleToolkit controls.

**Comment by KannanKrish** [comment]
Thanks for the update

**Comment by RadekVyM** [comment]
[New version](https://github.com/RadekVyM/SimpleToolkit/releases/tag/v4.0.0) with .NET 8 support has been released.

**Comment by KannanKrish** [comment]
Great! thanks for the new release.

**Pull request closed without merging**
